# Do-Not-Delete items (guarded). Add paths/keywords here.
keywords:
  - "DaVinci Resolve Pro"
  - "Speechelo"
  - "Scriptole"
  - "Sublime Text"
  - "Blender"
  - "Blinder"
  - "Linly"
  - "Talking Head"
  - "Pinokio"
  - "Pinocchio"
  - "FX"
  - "VFX"
  - "SFX"
  - "pipelines"
paths: []
